### ISSUE TITLE
dubbo使用redis注册中心的系列问题 | KL博客

### ISSUE THREAD

**Issue by klboke** [klboke/klblog-talk#17]
http://www.kailing.pub/article/index/arcid/202.html 

 KL博客，kl博客，java,php学习心得技术分享，一个爱折腾的程序猿

**Comment by klboke** [comment]
新增一个注意事项，假如使用redis作为注册中心，一定要配套一个dubbo admin，因为过期的和废弃的提供者服务是基于dubbo admin来清理的，没有部署的话，这些脏数据会一直保留在reids注册中心

**Comment by heli-boop** [comment]
grpc.manager.GRPCManagerProvider -40296 [main] ERROR [] - Failed to bind

grpc.GRPCServerException: Failed to bind

**Comment by klboke** [comment]
> @yunqianglee
> grpc.manager.GRPCManagerProvider -40296 [main] ERROR [] - Failed to bind
> 
> grpc.GRPCServerException: Failed to bind

???

**Comment by heli-boop** [comment]
是这样的 ；我的用docker部署的 ，按照你的镜像文件，然后里面的realhost是写死的 ，docker run --add-host localhost:ip ，ip就是我realhost写死的部分；启动的时候查看skywalking-collector-server.log 日志里面说GRPCManagerProvider -40296 [main] ERROR [] - Failed to bind 端口绑定不了

**Comment by heli-boop** [comment]
org.apache.skywalking.apm.collector.server.grpc.GRPCServerException: Failed to bind
	at org.apache.skywalking.apm.collector.server.grpc.GRPCServer.start(GRPCServer.java:101) ~[server-component-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.grpc.manager.GRPCManagerProvider.lambda$notifyAfterCompleted$0(GRPCManagerProvider.java:71) ~[collector-grpc-manager-provider-5.0.0-GA.jar:5.0.0-GA]
	at java.util.HashMap$Values.forEach(HashMap.java:980) [?:1.8.0_111]
	at org.apache.skywalking.apm.collector.grpc.manager.GRPCManagerProvider.notifyAfterCompleted(GRPCManagerProvider.java:69) [collector-grpc-manager-provider-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.core.module.BootstrapFlow.notifyAfterCompleted(BootstrapFlow.java:67) [apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.core.module.ModuleManager.init(ModuleManager.java:69) [apm-collector-core-5.0.0-GA.jar:5.0.0-GA]
	at org.apache.skywalking.apm.collector.boot.CollectorBootStartUp.main(CollectorBootStartUp.java:45) [apm-collector-boot-5.0.0-GA.jar:5.0.0-GA]
Caused by: java.io.IOException: Failed to bind
	at io.grpc.netty.NettyServer.start(NettyServer.java:252) ~[grpc-netty-1.14.0.jar:1.14.0]
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:163) ~[grpc-core-1.14.0.jar:1.14.0]
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:78) ~[grpc-core-1.14.0.jar:1.14.0]
	at org.apache.skywalking.apm.collector.server.grpc.GRPCServer.start(GRPCServer.java:99) ~[server-component-5.0.0-GA.jar:5.0.0-GA]
	... 6 more
Caused by: java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method) ~[?:1.8.0_111]

**Comment by klboke** [comment]
> @yunqianglee
> 是这样的 ；我的用docker部署的 ，按照你的镜像文件，然后里面的realhost是写死的 ，docker run --add-host localhost:ip ，ip就是我realhost写死的部分；启动的时候查看skywalking-collector-server.log 日志里面说GRPCManagerProvider -40296 [main] ERROR [] - Failed to bind 端口绑定不了

兄弟，这个是dubbo注册中心的文章，所以我有点蒙。然后你的问题，要看你docker的网络模式是什么，你设置的这个不一定是容器里面的ip

**Comment by heli-boop** [comment]
http://kailing.pub/article/index/arcid/221.html 我连的是这个 尴尬了

**Comment by heli-boop** [comment]
我设置的宿主机的ip，网络模式就是docker默认的 不知道大佬能不能支出具体问题

**Comment by klboke** [comment]
https://github.com/klboke/klblog-talk/issues/172 到这个聊吧
